# Generated by Django 4.2.3 on 2026-08-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hydrology", "0001_initial"),
        ("exposure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("storm_mm", models.FloatField()),
                ("multiplier", models.FloatField()),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="exposure.floodevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonalOutlook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_label", models.CharField(default="OND 2026", max_length=32)),
                ("enso_phase", models.CharField(default="El Nino", max_length=32)),
                ("probability_above_normal", models.FloatField(default=0.875)),
                ("source_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeasonalWardRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("displaced", models.PositiveIntegerField(default=0)),
                ("buildings_affected", models.PositiveIntegerField(default=0)),
                ("loss_kes", models.FloatField(default=0.0)),
                ("risk_band", models.CharField(default="Low", max_length=16)),
                (
                    "outlook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ward_risks",
                        to="outlook.seasonaloutlook",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ward_risks",
                        to="outlook.scenariorun",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_risks",
                        to="exposure.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["ward", "scenario__multiplier"],
            },
        ),
        migrations.AddField(
            model_name="scenariorun",
            name="outlook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario_runs",
                to="outlook.seasonaloutlook",
            ),
        ),
        migrations.AddField(
            model_name="scenariorun",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hydrology.forecastrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="seasonalwardrisk",
            constraint=models.UniqueConstraint(
                fields=("outlook", "ward", "scenario"),
                name="unique_outlook_ward_scenario",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariorun",
            constraint=models.UniqueConstraint(
                fields=("outlook", "key"), name="unique_outlook_scenario"
            ),
        ),
    ]
