# Generated by Django 4.2.3 on 2026-08-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exposure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_depth_m", models.FloatField(default=0.0)),
                ("extent_fraction", models.FloatField(default=0.0)),
                ("duration_h", models.FloatField(default=0.0)),
                ("people_affected", models.PositiveIntegerField(default=0)),
                ("people_displaced", models.PositiveIntegerField(default=0)),
                ("buildings_affected", models.PositiveIntegerField(default=0)),
                ("roads_submerged_m", models.FloatField(default=0.0)),
                ("facilities_at_risk", models.JSONField(blank=True, default=list)),
                ("loss_usd", models.FloatField(default=0.0)),
                ("hazard_index", models.FloatField(default=0.0)),
                ("exposure_index", models.FloatField(default=0.0)),
                ("vulnerability_index", models.FloatField(default=0.0)),
                ("risk_score", models.FloatField(default=0.0)),
                ("risk_band", models.CharField(default="Low", max_length=16)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ward_risk",
                        to="exposure.floodevent",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_results",
                        to="exposure.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_score"],
            },
        ),
        migrations.CreateModel(
            name="DamageResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth_m", models.FloatField()),
                ("duration_h", models.FloatField()),
                ("damage_pct", models.FloatField()),
                ("loss_usd", models.FloatField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_results",
                        to="exposure.building",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_results",
                        to="exposure.floodevent",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="damage_results",
                        to="exposure.ward",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="wardrisk",
            constraint=models.UniqueConstraint(
                fields=("event", "ward"), name="unique_event_ward_risk"
            ),
        ),
    ]
