# Generated by Django 4.2.3 on 2026-08-30 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("impact", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="damageresult",
            old_name="loss_usd",
            new_name="loss_kes",
        ),
        migrations.RenameField(
            model_name="wardrisk",
            old_name="loss_usd",
            new_name="loss_kes",
        ),
    ]
