# Generated by Django 4.2.3 on 2026-08-30 06:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hydrology", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_id", models.CharField(max_length=32, unique=True)),
                (
                    "bldg_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                        ],
                        default="residential",
                        max_length=16,
                    ),
                ),
                (
                    "footprint",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                ("area_m2", models.FloatField(default=100.0)),
                ("replacement_value_per_m2", models.FloatField(default=400.0)),
            ],
        ),
        migrations.CreateModel(
            name="CriticalFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "fclass",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("school", "School"),
                            ("water_works", "Water treatment"),
                            ("substation", "Power substation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="FloodEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("duration_h", models.FloatField(default=24.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="hydrology.forecastrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_id", models.CharField(max_length=32, unique=True)),
                ("highway", models.CharField(blank=True, max_length=32)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("county", models.CharField(blank=True, max_length=128)),
                ("population", models.PositiveIntegerField(default=0)),
                ("vulnerability_index", models.FloatField(default=0.5)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FloodPolygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_h", models.PositiveIntegerField(default=0)),
                ("depth_m", models.FloatField()),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flood_polygons",
                        to="exposure.floodevent",
                    ),
                ),
            ],
        ),
    ]
