# Generated by Django 4.2.3 on 2026-08-30 06:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Basin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hybas_id", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("upstream_area_km2", models.FloatField(default=0.0)),
                ("response_time_h", models.FloatField(default=6.0)),
                (
                    "downstream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upstream_basins",
                        to="hydrology.basin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForecastRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("init_time", models.DateTimeField()),
                ("horizon_h", models.PositiveIntegerField(default=168)),
                ("source", models.CharField(default="synthetic", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-init_time"],
            },
        ),
        migrations.CreateModel(
            name="River",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                ("manning_n", models.FloatField(default=0.035)),
                ("bankfull_q_m3s", models.FloatField(default=50.0)),
                ("slope", models.FloatField(default=0.002)),
                (
                    "basin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="river",
                        to="hydrology.basin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DischargeForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_time", models.DateTimeField()),
                ("lead_h", models.PositiveIntegerField()),
                ("q50_m3s", models.FloatField()),
                ("q10_m3s", models.FloatField(blank=True, null=True)),
                ("q90_m3s", models.FloatField(blank=True, null=True)),
                (
                    "basin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="hydrology.basin",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="hydrology.forecastrun",
                    ),
                ),
            ],
            options={
                "ordering": ["basin", "lead_h"],
                "indexes": [
                    models.Index(
                        fields=["run", "basin"], name="hydrology_d_run_id_5dc881_idx"
                    )
                ],
            },
        ),
    ]
